@baseUrl = http://dbhuan.local/api/id

### Tạo user

POST {{baseUrl}}/v1/users 
Content-Type: application/json

{
    "username": "dbhuan4@test.com",
    "firstName": "Huân",
    "lastName": "Dương",
    "password": "123456"
}

### Lấy thông tin user hiện tại

GET {{baseUrl}}/v1/users/me
Content-Type: application/json