@baseUrl = http://dbhuan.local/api/id

@accessToken = paSODgNn-98Q9iSAjqit3G5liiu3TjuzbN1ItvrWmdc=

### Tạo user

POST {{baseUrl}}/v1/users 
Content-Type: application/json

{
    "username": "dbhuan4@test.com",
    "firstName": "Huân",
    "lastName": "Dương",
    "password": "123456"
}

### Lấy thông tin user hiện tại

GET {{baseUrl}}/users/cu 
Content-Type: application/json
Authorization: Bearer {{accessToken}}